[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"

# Optimizer
optimizer = true
optimizer_runs = 200

# RPC endpoints
[rpc_endpoints]
mantle_sepolia = "${MANTLE_SEPOLIA_RPC}"
mantle = "${MANTLE_MAINNET_RPC}"

# Etherscan/Block Explorer verification
[etherscan]
mantle_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.sepolia.mantle.xyz/api" }
mantle = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.mantle.xyz/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
